name: Build alpha apk

on:
  workflow_dispatch:

env:
  VARIANT: alpha
  TAG: alpha
  ZIP: app-alpha.zip

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository files
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build & assemble
        run: ./gradlew build assemble${{ env.VARIANT }}

      - name: Zip ${{ env.VARIANT }} apk as ${{ env.ZIP }}
        run: zip -j ${{ env.ZIP }} app/build/outputs/apk/${{ env.VARIANT }}/app-${{ env.VARIANT }}.apk

      - name: Create or update tag
        run: |
          git tag --force ${{ env.TAG }}
          git push --force origin tag ${{ env.TAG }}

      - name: Upload ${{ env.ZIP }} to ${{ env.TAG }} release
        run: |
          gh release create ${{ env.TAG }} --title "Release ${{ env.TAG }}" --notes "Alpha release"
          gh release upload ${{ env.TAG }} ${{ env.ZIP }} --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
